# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-04-03 17:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Type',
            new_name='Category',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='type',
            new_name='category',
        ),
    ]
